# Generated by Django 5.1.1 on 2024-10-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='concesionario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='marca',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='correo_electronico',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='marca',
            name='pais_origen',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionario.marca')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concesionario.vehiculo'),
        ),
        migrations.DeleteModel(
            name='Concesionario',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
