# Generated by Django 5.1.1 on 2024-11-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionario', '0003_marca_bandera_marca_logo_alter_vehiculo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.BigIntegerField(),
        ),
    ]
