# Generated by Django 5.1.1 on 2024-11-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionario', '0004_alter_vehiculo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
    ]
